apiVersion: v1
kind: Service
metadata:  
  name: vrtu
  labels:
    app: vrtu
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: vrtu
spec:
  type: "LoadBalancer"
  ports:
  - name: "502"
    port: 502
    targetPort: 502  
  selector:
    app: vrtu
    release: {{ .Release.Name }}
    component: vrtu
status:
  loadBalancer: {}