apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}-vrtu
  labels:
    app: {{ template "fullname" . }}-vrtu
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    component: vrtu
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: vrtu
      component: vrtu
  template:
    metadata:
      labels:
        app: vrtu
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        release: "{{ .Release.Name }}"
        heritage: "{{ .Release.Service }}"
        component: vrtu
    spec:      
      containers:
        - name: vrtu     
          image: {{ .Values.image1.repository }}:{{ .Values.image1.tag }}
          imagePullPolicy: {{ .Values.image1.pullPolicy }}
          env:          
          - name: VRTU_ClaimTypes            
            valueFrom:
              secretKeyRef:
                name: {{ template "fullname" . }}
                key: claimTypes  
          - name: VRTU_ClaimValues            
            valueFrom:
              secretKeyRef:
                name: {{ template "fullname" . }}
                key: claimValues 
          - name: VRTU_SymmetricKey          
            valueFrom:
              secretKeyRef:
                name: {{ template "fullname" . }}
                key: symmetricKey  
          - name: VRTU_Issuer        
            valueFrom:
              secretKeyRef:
                name: {{ template "fullname" . }}
                key: issuer   
          - name: VRTU_Audience        
            valueFrom:
              secretKeyRef:
                name: {{ template "fullname" . }}
                key: audience 
          - name: VRTU_LifetimeMinutes       
            valueFrom:
              secretKeyRef:
                name: {{ template "fullname" . }}
                key: lifetimeMinutes           
          - name: VRTU_Hostname    
            valueFrom:
              secretKeyRef:
                name: {{ template "fullname" . }}
                key: hostname
          - name: VRTU_StorageConnectionString
            valueFrom:
              secretKeyRef:
                name: {{ template "fullname" . }}
                key: storageConnectionString               
          - name: VRTU_Container
            valueFrom:
              secretKeyRef:
                name: {{ template "fullname" . }}
                key: container
          - name: VRTU_Filename
            valueFrom:
              secretKeyRef:
                name: {{ template "fullname" . }}
                key: filename
          - name: VRTU_InstrumentationKey
            valueFrom:
              secretKeyRef:
                name: {{ template "fullname" . }}
                key: instrumentationKey 
          - name: VRTU_VirtualRtuId
            valueFrom:
              secretKeyRef:
                name: {{ template "fullname" . }}
                key: virtualRtuId
          - name: VRTU_LogLevel
            valueFrom:
              secretKeyRef:
                name: {{ template "fullname" . }}
                key: logLevel 
          - name: APPINSIGHTS_INSTRUMENTATIONKEY
            valueFrom:
              secretKeyRef:
                name: {{ template "fullname" . }}
                key: instrumentationKey           
          ports:
          - containerPort: 502
          readinessProbe:
            tcpSocket:
              port: 502            
          livenessProbe:
            tcpSocket:
              port: 502                     