replicaCount: 1
loggerTypes: "Console;Debug"
loglevel: "Warning"

image1:
  ## Image location, NOT including the tag
  repository: skunklab/virtualrtu-gateway
  ## Image tag
  tag: v3.0 
  pullPolicy: IfNotPresent
  

service: 
  type: ClusterIP




